# Generated by Django 3.2 on 2021-12-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocked',
            old_name='start_on',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='blocked',
            old_name='end_on',
            new_name='check_out',
        ),
    ]
